/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CPUTemperatureMeter
#define HEADER_CPUTemperatureMeter
/*
htop
(C) 2004-2006 Hisham H. Muhammad
(c) 2013 Morgan Blackthorne
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#define KELVIN     0
#define CELSIUS    1
#define FAHRENHEIT 2

extern int CPUTemperatureMeter_attributes[];

#ifdef HAVE_LIBNCURSESW
#define DEG_SYMBOL "\xc2\xb0"
#else
#define DEG_SYMBOL "\'"
#endif

double celcius_to_scale(double temp, int scale);

extern MeterClass CPUTemperatureMeter_class;

#endif
