/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_FanRPMMeter
#define HEADER_FanRPMMeter
/*
htop
(c) 2013 Morgan Blackthorne
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int FanRPMMeter_attributes[];

extern MeterClass FanRPMMeter_class;

#endif
