/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CPUTemperature
#define HEADER_CPUTemperature
/*
htop - darwin/CPUTemperature.h
(C) 2004-2006 Hisham H. Muhammad
(c) 2013 Morgan Blackthorne
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

void CPUTemperature_getData(double* values);

#endif
