/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_FanRPM
#define HEADER_FanRPM
/*
htop - darwin/FanRPM.h
(C) 2004-2006 Hisham H. Muhammad
(c) 2013 Morgan Blackthorne
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

void FanRPM_getData(double* rpm);

#endif
